### ISSUE TITLE
Node version?

### ISSUE THREAD

**Issue by mwalkerwells** [purescript-node/purescript-node-fs#36]
What is the node compatibility for this & how is it enforced?

**Comment by hdgarrood** [comment]
Up to now it hasn’t really been a problem since the node apis tend to be fairly stable. We only consistently test on one version of node, which is the one in the .travis.yml file (currently 6.x); that’s as far as enforcement goes.

We did decide to drop support for versions before 4.x a while ago. If something were to stop working on 4.x or 5.x now, I’m not sure whether we would decide to drop support for those as well or to treat it as a bug and fix it; it would depend on the issue, I think.

**Comment by mwalkerwells** [comment]
Ok, that's really helpful. I was looking for an example because I'm writing a Dropbox ffi & couldn't figure out how to indicate node version compatibility. I wanted to use certain ES language features, which are dependent on the version of V8 shipped with node.
